# Functions

### 1. Define a Sum Function Which accepts variable number of integers as an arguments. 

In [13]:
## sum function
x = input('Enter the first argument')
y = input('Enter the second argument')

def sum_(x,y):
    return x+y

#     for each in args:
#         total+=1
#     print(total)
    
print(return)  


SyntaxError: invalid syntax (<ipython-input-13-a8c5011253df>, line 12)

In [29]:
# func
args = input('enter the argument')

def sum(*args):
    result = 0

    for each in args:
        if type(each) in (int,float):
        result += each

    return result

print(sum(args))
# print(sum(10, 20, 30))
# print(sum(10, 20, 30, 40))

IndentationError: expected an indented block (<ipython-input-29-ba1e6d090e30>, line 9)

### 2. Create a list With  Square of all numbers from 1 to 10  using List Comprehension. 

In [33]:
isquare = [each**2 for each in list(range(1,11))]
print(isquare)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### 3. Write a lambda function which find square of a number 

In [10]:
data = int(input('Enter the number: '))

la = lambda x:x**2
print(la(data))


Enter the number: 55
3025


### 4. Declare a List With Numbers From 1 to 100 using List Comprehension. 
Use the lambda and filter function  to filter all even numbers. 
( Syntax for filter Function :  
 filter(function, iterable)    
 iterable can be list ,tuples dict etc.. 

In [33]:
squares = [i**2 for i in range(1,101)]
# print(squares)
sq_list = list(filter(lambda x:x%2==0, squares))
print(sq_list)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000]


# File Handling

### 1. Python program to read the content of the file

In [4]:
file = open(file = 'Assignment2.txt', mode ='w')
file.write("This is an assignment file of week 2")
file.close()

In [5]:
file = open(file = 'Assignment2.txt', mode ='r')
print(file.read())
file.close()

This is an assignment file of week 2


### 2. Python program to count the number of Words in a Text file

In [6]:
file = open(file = 'Assignment2.txt', mode ='r')
filestr = print(file.read())
print(filestr)
file.close()
# word_count = 0
word_count = len(filestr.split())
print("Number of words = " word_count)


SyntaxError: invalid syntax (<ipython-input-6-a197703658ed>, line 7)

In [7]:
# The default mode is 'rt' (open for reading text).

file = open(file = 'Assignment2.txt', mode ="rt")
data = file.read()
words = data.split()
print('Number of words in text file :', len(words))

Number of words in text file : 8


### 3. Python program to copy the content of one file into another file.

In [7]:
file = open(file = 'Assignment2.txt', mode ='w')
file.write("This is an assignment file of week 2")
file.write("\nThie is the first line.\nThis is the second line.\nThis is third line.")
file.close()
print('Below is the content in the first file:\n')
file = open(file = 'Assignment2.txt', mode ='r')
print(file.read())
file.close()

# copy 'Assignment2.txt' in 'Assignment2.1.txt'
with open("Assignment2.txt") as f1:
    with open("Assignment2.1.txt", "w") as f2:
        for line in f1:
            f2.write(line)
print('\n\n\n\nBelow is the content in the second file:\n')
file = open(file = 'Assignment2.1.txt', mode ='r')
print(file.read())
file.close()


Below is the content in the first file:

This is an assignment file of week 2
Thie is the first line.
This is the second line.
This is third line.




Below is the content in the second file:

This is an assignment file of week 2
Thie is the first line.
This is the second line.
This is third line.


### 4. Python program to read a file and capitalise the first letter of every word in the file

In [8]:
filename = input('Enter the file name: ')

with open(filename, 'r') as file:
    for eachline in file:
        lines = eachline.title()
        print(lines)
    file.close()

Enter the file name: Assignment2.1.txt
This Is An Assignment File Of Week 2

Thie Is The First Line.

This Is The Second Line.

This Is Third Line.


# Regular Expression


### 1. Validate an email id using regular expression

In [9]:
import re

In [14]:
## Create a pattern for email id
## pattern building

email = input("enter the email id: ")

pattern = "^([A-Za-z0-9_\.\-]+)@([A-za-z-]+)\.(com|edu|org)$"
if re.search(pattern,email):
    print('Your email ID is validated successfully')
else:
    print('Invalid email ID')
    

enter the email id: papapapap_adjknasd@yahoo.org
Your email ID is validated successfully


### 2. Validate a mobile Phone Number suing Regular Expression 

In [18]:
## Create a pattern for phone number
## pattern building

ph_no = input("Enter the 10-digit phone number")

pattern = "^(\d{10})$"
if re.search(pattern, ph_no):
     print('Your phone number is validated successfully')
else:
    print('Invalid phone number')

Enter the 10-digit phone number98282
Invalid phone number


### 3. Validate a credit cad number using Regular Expression

In [21]:
## Create a pattern for 16 digit credit acrd number
## pattern building

creditcard_no = input("Enter the 16-digit credit card number, 'Ex- abcd-abcd-abcd-abcd': ")

pattern = "^(\d{4}-\d{4}-\d{4}-\d{4})$"
if re.search(pattern, creditcard_no):
     print('Your credit card number is validated successfully')
else:
    print('Invalid credit card number')

Enter the 16-digit credit card number, 'Ex- abcd-abcd-abcd-abcd': 4563-3721-2887-0987
Your credit card number is validated successfully


# Numpy

### 1.Write a Python program to print the NumPy version in your system.

In [2]:
import numpy as np
print(np.__version__)

1.16.5


### 2. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. 

In [6]:
arr = np.random.randint(1,30,24).reshape(6,4)
arr

array([[22, 22, 12, 21],
       [10, 12, 22, 28],
       [ 4,  8,  5, 14],
       [13,  7, 10, 12],
       [23, 16, 12, 14],
       [14, 20, 25,  3]])

### 3. Write a Python program to create an array with values ranging from 12 to 38. 

In [10]:
arr= np.random.randint(12,38,24).reshape(6,4)
arr

array([[32, 24, 30, 36],
       [26, 21, 34, 24],
       [21, 27, 21, 25],
       [32, 16, 23, 24],
       [15, 33, 24, 28],
       [22, 19, 31, 36]])

#### 4. Write a Python program to convert a list and tuple into arrays. 

In [13]:
list_ = [1,2,3,4,5,6,7,8,9,10]
print('converted array is:\n')
print(np.asarray(list_))

converted array is:

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
tuple_ = (1,2,3,4,5,6,7,8,9,10)
print('converted array is:\n')
print(np.asarray(tuple_))

converted array is:

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
tuple_ = ([1,2,3,4,5],[6,7,8,9,10])
print('converted array is:\n')
print(np.asarray(tuple_))

converted array is:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 5. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [21]:
import numpy as np

arr1  = np.array([1,2,3,4,5,6,7,8,9,10])

print("No. if elements in array: ", arr1.size)
print("Length of one array element in bytes: ", arr1.itemsize)
print("Total bytes consumed by the elements of the array: ", arr1.nbytes)

    

Size of the array:  10
Length of one array element in bytes:  4
Total bytes consumed by the elements of the array:  40


### 6. Write a Python program compare two arrays using numpy. 

In [28]:
arr1 = np.random.randint(1,14,12).reshape(2,6)
arr2 = np.random.randint(1,10,12).reshape(2,6)
print('First array:\n',arr1)
print('Second array:\n',arr2)

arr3 = np.in1d(arr1,arr2)
print(arr3)

# if arr1>arr2:
#     print(arr1)
# elif arr1<arr2:
#     print(arr2)
# else:
#     print('Both are equal')

    

First array:
 [[5 1 4 7 8 7]
 [9 4 3 2 9 2]]
Second array:
 [[1 8 8 2 5 5]
 [1 3 8 1 5 9]]
[ True  True False False  True False  True False  True  True  True  True]


### 7. Write a Python program to get the number of nonzero elements in an array. 

In [38]:
arr1 = np.random.randint(0,10,4).reshape(2,2)
print(arr1)
print(np.count_nonzero(arr1))

[[3 0]
 [1 6]]
3


### 8. Write a Python program to check whether the numpy array is empty or not. 

In [46]:
arr3 = np.array([])
arr2 =np.array([1,2,3])
print(arr3.size,arr2.size)
# print(arr2.size)

0 3


### 9. Write a Python program to get the powers of an array values element-wise. 

In [55]:
arr1 = np.random.randint(1,16,24).reshape(6,4)
print(arr1)
print("\n\nBelow i the calculated array:\n")
print(np.power(arr1,2))

[[ 7  1  4  1]
 [10 12 13  3]
 [ 6  8 13  7]
 [ 8 11  6 10]
 [ 9  8 10 13]
 [ 8  4 11  5]]


Below i the calculated array:

[[ 49   1  16   1]
 [100 144 169   9]
 [ 36  64 169  49]
 [ 64 121  36 100]
 [ 81  64 100 169]
 [ 64  16 121  25]]
