In [1]:
# import package
import numpy as np

In [3]:
# dir(np)

In [4]:

list_ = [1,2,3]
arr = np.array(list_)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
type(list_[0])

int

In [7]:
type(arr[0])

numpy.int32

In [8]:
list_ = [1,2,3, 'bangalore', 'Hyd']
arr = np.array(list_)
print(arr)
print(type(arr))

['1' '2' '3' 'bangalore' 'Hyd']
<class 'numpy.ndarray'>


In [12]:
print(type(arr[0]))
print(type(arr[3]))

<class 'numpy.str_'>
<class 'numpy.str_'>


In [13]:
list2  = list(range(1,11))

In [14]:
list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
list2*2 # concating and broadcasting not supported

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
# multipl each element by 2
arr = np.array(list2)
arr*2    # broadcasting supported

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Creating arrays
- 


In [21]:
## single dimentional
arr = np.empty(shape = 5)
arr


array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313])

In [33]:
# multidimentional dimentional
arr = np.empty(shape = (2,3), dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
##
arr = np.ones(shape =5)
arr

array([1., 1., 1., 1., 1.])

In [28]:
##
arr = np.ones(shape = (3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
##
arr = np.zeros(shape =5)
arr

array([0., 0., 0., 0., 0.])

In [31]:
##
arr = np.zeros(shape =(3,4,5))
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
##
arr = np.linspace(1,20,10) # generate evenly spaced numbers
print(arr)
print(type(arr))

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
<class 'numpy.ndarray'>


In [43]:
arr = np.arange(1,10,2, dtype=float)
print(arr)
print(type(arr))

[1. 3. 5. 7. 9.]
<class 'numpy.ndarray'>


In [48]:
arr = np.random.rand(2)
print(arr)
print(type(arr))

[0.03413981 0.29997123]
<class 'numpy.ndarray'>


In [58]:
arr = np.random.rand(2,3)
print(arr)
print(type(arr))

[[0.17363167 0.12828097 0.67688001]
 [0.04909888 0.12867888 0.88763201]]
<class 'numpy.ndarray'>


In [60]:
arr = np.random.randn(5,2)
print(arr)
print(type(arr))

[[-1.87345775  0.85409824]
 [-1.51907187  1.07106452]
 [ 0.60190675  0.81271871]
 [-0.00828149  0.58479569]
 [ 0.79203265 -1.16263466]]
<class 'numpy.ndarray'>


In [56]:
arr = np.random.randint(2,7)
print(arr)
print(type(arr))

2
<class 'int'>


In [61]:
arr = np.random.randn(5,2)
print(arr)
print(type(arr))

[[-0.35696526 -0.19268575]
 [ 0.69890767 -0.87405148]
 [ 1.17143088  0.18148059]
 [ 1.49158129  0.27627912]
 [ 0.69189473  0.35393738]]
<class 'numpy.ndarray'>


In [62]:
arr[2][1]

0.18148059012239953

In [67]:
### a[i][j] = a[i,j], both are valid for array object
arr[2,1] = 55
arr[2,1]

55.0

In [74]:
## reshaping the array

arr = np.array([1,2,3,4])
print(arr)
n_arr = arr.reshape((2,2))
print(n_arr)

[1 2 3 4]
[[1 2]
 [3 4]]


In [75]:
# np.mean(), min, np.min(), np.std(), np.max()


In [76]:
## impact of + operator

arr1 = np.arange(1,11,1).reshape(2,5)
print(arr1)
arr2 = np.random.rand(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.3382715  0.75029149 0.65913184 0.78614149 0.67947349]
 [0.79524264 0.95080111 0.99524558 0.82502378 0.62206201]]


In [77]:
## element vist addition
arr1+arr2

array([[ 1.3382715 ,  2.75029149,  3.65913184,  4.78614149,  5.67947349],
       [ 6.79524264,  7.95080111,  8.99524558,  9.82502378, 10.62206201]])

In [78]:
## impact of * operator
arr1*arr2

array([[0.3382715 , 1.50058298, 1.97739551, 3.14456598, 3.39736744],
       [4.77145584, 6.65560774, 7.96196466, 7.42521402, 6.22062006]])

In [79]:
6*0.79524264 


4.77145584

In [80]:
## matrix multiplication

arr1 = np.arange(1,11,1).reshape(2,5)
print(arr1)
arr2 = np.random.rand(5,2)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.05245078 0.62640556]
 [0.24862937 0.72397425]
 [0.04647258 0.13065799]
 [0.71203204 0.44637877]
 [0.45117004 0.41328407]]


In [81]:
np.dot(arr1,arr2) # matrix multiplication

array([[ 5.79310564,  6.31826342],
       [13.34687972, 18.02176656]])

# Pandas
pandas is an open source, high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

- Series - 1D labedel, homogeneour array, size-immutable
- DataFrame - 2D labdled, size mutable tabular with potentially hetrogeneously typed column. (Important)
- Panel - 3D labedled, size-mutable array

In [85]:
## import package

import pandas as pd

In [88]:
s = pd.Series(data = [1,2,3])
print(type(s))

<class 'pandas.core.series.Series'>


In [89]:
print(s)

0    1
1    2
2    3
dtype: int64


In [91]:
s = pd.Series(data = [1,2,3], index = ['a','b','c'] )
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64


In [93]:
s = pd.Series(data = np.array(range(1,11)))
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32


In [96]:
s = pd.Series(data = [1,2,3.0,4])
s

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [97]:
s = pd.Series(data = [1,2,3.0,4], name = 'series1')
s

0    1.0
1    2.0
2    3.0
3    4.0
Name: series1, dtype: float64

In [99]:
s = pd.Series(data = {'a':'bangalore', 'b': 'Hyd', 'c':'Mumbai'})
s

a    bangalore
b          Hyd
c       Mumbai
dtype: object

##### Accessing elements



In [104]:
s = pd.Series(data = [1,2,3,4,5,6,7,8,12])
print(s[2:6])

2    3
3    4
4    5
5    6
dtype: int64


In [109]:
s = pd.Series(data = [1,2,3,4,5,6,12], index = ['a','b','c','d','e','f','g'])

print(s[2:6])

c    3
d    4
e    5
f    6
dtype: int64


In [110]:
## accessing by label
print(s['e'])

5


In [114]:
s = pd.Series(data = 5, index = np.arange(8))
s

0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
dtype: int64

## dataframe

In [115]:
##
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [118]:
## DataFrame from list

df = pd.DataFrame(data = np.arange(5))
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [121]:
df

0
0  0
1  1
2  2
3  3
4  4

In [123]:
df = pd.DataFrame(data = np.arange(50).reshape(2,25))
df

0   1   2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  \
0   0   1   2   3   4   5   6   7   8   9  ...  15  16  17  18  19  20  21   
1  25  26  27  28  29  30  31  32  33  34  ...  40  41  42  43  44  45  46   

   22  23  24  
0  22  23  24  
1  47  48  49  

[2 rows x 25 columns]

In [130]:
df = pd.DataFrame(data = np.arange(5), columns=['c1'], index = ['a','d','e','a','a'])
df

c1
a   0
d   1
e   2
a   3
a   4

In [133]:
df = pd.DataFrame(data = np.arange(5).reshape(6,2), columns=['c1'], index = ['a','d','e','a','a'])
df

ValueError: cannot reshape array of size 5 into shape (6,2)

In [132]:
### nested list
df = pd.DataFrame(data = [[1,2,3],[4,5,6]], columns=['c1','c2','c3'], index=['a','b'])
df

c1  c2  c3
a   1   2   3
b   4   5   6

In [134]:
### nested list
df = pd.DataFrame(data = [[1,2,3],[4,5]], 
                  columns=['c1','c2','c3'], 
                  index=['a','b'])
df

c1  c2   c3
a   1   2  3.0
b   4   5  NaN

In [138]:
### nested list
df = pd.DataFrame(data = [[1,2,'3',4],[4,5]], 
                  columns=['c1','c2','c3','c4'], 
                  index=['a','b'])
df

c1  c2    c3   c4
a   1   2     3  4.0
b   4   5  None  NaN

In [143]:
### nested list - dictionary
df = pd.DataFrame(data = {'a':'bangalore','b':'mumbai','c':'chennai','d':'kolkata'} ,
                 index = ['e','f','g','h'])
df

a       b        c        d
e  bangalore  mumbai  chennai  kolkata
f  bangalore  mumbai  chennai  kolkata
g  bangalore  mumbai  chennai  kolkata
h  bangalore  mumbai  chennai  kolkata

In [144]:
##
# accessing