In [2]:
# Python: Variables
        # - int
        # - str
        # - float
        # - complex
        # - bool
        # - list
        # - tuple
        # - dict
        # - inbuilt

In [69]:
v1 = 5
v2 = 'Hi'
v3 = 5.532
v4 = 2+3j
v5 = True
v6 = [1,2,3,4,5], ['a','b','c']
v7 = (1,2,3,4,5)
v8 = {'A':1, 'B':2, 'C':3}
# v8 = {'k':'v'}
# v7= (3,4,5)

In [70]:
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
print(v6)
print(v7)
print(v8)

5
Hi
5.532
(2+3j)
True
([1, 2, 3, 4, 5], ['a', 'b', 'c'])
(1, 2, 3, 4, 5)
{'A': 1, 'B': 2, 'C': 3}


In [71]:
print(type(v1))
print(type(v2))
print(type(v3))
print(type(v4))
print(type(v5))
print(type(v6))
print(type(v7))
print(type(v8))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'tuple'>
<class 'tuple'>
<class 'dict'>


In [87]:
#indexing and slicing

k = "string"
new_str = k[2:6]
print(new_str)

ring


In [82]:
# print(k[1:7:1])


In [105]:
s1 = 5
s2 = 4
s3 = s1---s2
s3

1

In [59]:
# check if the str has and number or spl char.
str1 = "hello123"
str2 = "hello123@&!"
str3 = "hello"

In [94]:
print(str1.isalnum())
print(str1.isalpha())
print(str1.isalnum())
print(type(True))

True
False
True
<class 'bool'>


In [95]:
# Operators and their precedences
var1 = 3
var2 = 2
print (var1*var2) #6
print (var1**var2) #9
print (var1/var2) #1.5
print (var1//var2) # 1
print (3//2.0) # 1.0
print (var1%var2) # 1


6
9
1.5
1
1.0
1


In [96]:
# Comparision operators
 ## always returs bool : True ot Flase
var1 = 3
var2 = 2
print (var1==var2) # False
print (var1!=var2) # True
print (var1>var2) #True
print (var1>=var2) #True
print (var1<var2) # False
print (var1<=var2) #False

False
True
True
True
False
False


In [112]:
# Logical operators: AND, OR, NOT
print(3!=5)

True


In [6]:
# Assignment OPerator
# =, +=, -=, /=, %=, //=

a=2
# b=3
# a+=2
# # a=a+2
a-=1 # (a=a-1)

In [7]:
print(a)

1


In [8]:
a=10
# a = a+5
# a +=5
# print (a) # 15
# a -=10
# print (a) #0
# a *=2
# print (a) #20
# a %=4
# print (a) #2.5
a /=5
print (a) #2.0
a //=5
print (a) #2

2.0
0.0


In [9]:
# identity operators: is, is not
    
#     Bool(True/False)
print(3 is not 4)

True


In [10]:
# Membership operator [ in , not in]

a = [1,2,3,[4,5,6]]
print(3 not in a)

False


In [11]:
q= ['bangalore','chennai','mumbai', 'delhi']

In [12]:
print('mysore' in q)

False


In [13]:
## inbuitl functions
# input()

In [17]:
num1 = int(input('Enter the first number'))
num2 = int(input('enter the second number'))

num3 = num1+num2
print(num3)

Enter the first number22
enter the second number33
55


In [18]:
print(type(num1))

<class 'int'>


In [16]:
# val1 = int(input('Enter the number'))
val1='123456789'
print (val1[0:]) # 1-9
print (val1[0:4]) #1-4
print (val1[-5:-1:]) #5-9
print (val1[-1:-3:-1])
print (val1[-4:-1:])
print (val1[-1::-1])
print (val1[::-1])

123456789
1234
5678
98
678
987654321
987654321


In [20]:
num1 = int(input('Enter the first number'))
num2 = int(input('enter the second number'))
num3 = num1+num2
t1 = int(input('enter the threshold'))
if num3>t1:
    print('threshold breach')
else:
    print('within threshold')

Enter the first number3
enter the second number2
enter the threshold12
within threshold


In [23]:
num1 = int(input('Enter the first number'))
if num1%2==0:
    print('even number')
else:
    print('Odd number')

Enter the first number22
even number


In [1]:
decipline = ['sci','com','art']
num1 = int(input('Enter the stedent marks'))
stm1 = input('Enter the decipline')

if (num1>=90) & (stm1 in decipline):
    print('first division and start performer in {}'.format(stm1))
    
elif (num1<90)&(num1>=60) & (stm1 in decipline):
    print('first division in {}'.format(stm1))
    
elif (num1<60)&(num1>=40) & (stm1 in decipline):
    print('Second division in {}'.format(stm1))

elif (num1<40)&(num1>=33) & (stm1 in decipline):
    print('Third division division in {}'.format(stm1))
else:
    (num1<33) & (stm1 in decipline)
    print('student is Faild in {}!!!'.format(stm1))


Enter the stedent marks55
Enter the deciplinesci
Second division in sci


In [3]:
n1 = int(input('Enter the number'))
if n1%2==0:
    print("even number")
else:
    print('Odd number')

Enter the number45
Odd number


In [10]:
num1 = int(input('Enter the first no.:'))
num2 = int(input('Enter the second no.:'))
num3 = int(input('Enter the threshold:'))
if (num1+num2)>num3:
    print('Threshold Breach')
elif: 
    (num1+num2)=num3:
    print('Threshold level reached')
else:
    (num1+num2)<num3:
    print (Threshold limit is there..;)
        

SyntaxError: invalid syntax (<ipython-input-10-4909892be276>, line 6)

In [48]:
n1 = int(input('Enter the first number'))
n2= int(input("Enter the secong no."))
f1 = input('Enter the operator')
if (f1=='+'):
    print('The additon of {n1} and {n2} is {n3}'.format(n1=n1, n2=n2, n3=n2+n1))
elif (f1=='-') & (n1>n2):
    print('The substraction of two numbers{n1} and {n2} are {n3}'.format(n1=n1, n2=n2, n3=n1-n2))
elif (f1=='-') & (n1<n2):
    print('The substraction of two numbers{n1} and {n2} are {n3}'.format(n1=n2, n2=n1, n3=n2-n1))
#         else:
#             print('The substraction of two numbers{n1} and {n2} are {n3}'.format(n1=n1, n2=n2, n3=n2-n1)  
elif (f1=='*'):
          print('The multiplication of two numbers {n1} and {n2} are {n3}'.format(n1=n2, n2=n1, n3=n2*n1))
elif (f1=="/")&(n2!=0):
    print('The division of two numbers {n1} and {n2} are {n3}'.format(n1=n2, n2=n1, n3=n1/n2))
elif (n2==0):
    print('Denominator can not be zero')
else:
    print('Wrong input')

Enter the first number3
Enter the secong no.0
Enter the operator/
Denominator can not be zero


### WHile

In [1]:
x=10
while (x>0):
    print(x)
    x-=1

10
9
8
7
6
5
4
3
2
1


In [6]:
for i in range(1,4):
    print(list(i))
    

TypeError: 'int' object is not iterable

In [13]:
x=1
n1 = int(input('enter the number greater than one'))
while x<n1:
    print(x)
    x+=1

enter the number greater than one2
1


In [15]:
num= int(input('Enter the phone number'))
name='Prabir Kumar'
print('My name is {} and my phone number is {}'.format(name,num))

Enter the phone number33
My name is Prabir Kumar and my phone number is 33


In [16]:
s = 'Hello'

In [17]:
s[2]

'l'

In [18]:
l=['a','b','c','d']

In [19]:
l.append('e')

In [20]:
print(list(l))


['a', 'b', 'c', 'd', 'e']


In [21]:
l[0]='new'

In [22]:
nest = [1,2,3,[3,4,['prince']]]

In [28]:
nest[3][2][0]

'prince'

In [29]:
l

['new', 'b', 'c', 'd']

In [33]:
l.remove('b')

In [34]:
l

['new', 'c', 'd']

## Dictionary

In [51]:
dict_ = {'key1':'r1','key2':123, 'key3':123}

In [52]:
dict_

{'key1': 'r1', 'key2': 123, 'key3': 123}

In [58]:
dict_['key1']

'r1'

In [60]:
dict_['key3']

123

In [61]:
d = {'k1':[1,2,3,4,5]}

In [64]:
d['k1'][:3]

[1, 2, 3]

In [65]:
p = {'key':{'inerkey':[1,2,3,4,5]}}

In [67]:
p['key']['inerkey'][2]

3

In [68]:
ML=[1,2,3,4,5,6,7]

In [93]:
ML.append='p'

AttributeError: 'list' object attribute 'append' is read-only

In [71]:
ML

[1, 2, 3, 'new', 5, 6, 7]

### tuple

In [86]:
t = (1,2,3,4,5,[6,7,8,9])

In [87]:
t

(1, 2, 3, 4, 5, [6, 7, 8, 9])

In [98]:
t[5].append('p')

In [96]:
t[5][2]

11

In [99]:
t

(1, 2, 3, 4, 5, [6, 7, 11, 9, 'p'])

In [100]:
p1=t

In [101]:
p1

(1, 2, 3, 4, 5, [6, 7, 11, 9, 'p'])

In [2]:
t = ('a','b','c',['d','e','f'])

In [3]:
t

('a', 'b', 'c', ['d', 'e', 'f'])

In [4]:
t[3].append('4')

In [5]:
t

('a', 'b', 'c', ['d', 'e', 'f', '4'])

In [6]:
t[3][3]=5

In [7]:
t[3]

['d', 'e', 'f', 5]

In [8]:
t[3][2]='ee'

In [9]:
t[3][2].drop()

AttributeError: 'str' object has no attribute 'drop'

In [35]:
t

('a', 'b', 'c', ['d', 'e', 'ee', 5])

In [53]:
t[3].append(['9','8','7','5'])

In [54]:
t

('a', 'b', 'c', ['d', '77', 'ee', 5, ['9', '8', '7', '5']])

In [56]:
t[3].pop()

['9', '8', '7', '5']

In [57]:
t

('a', 'b', 'c', ['d', '77', 'ee', 5])

In [60]:
[1,2,3,4]
['b','c','d','e']
d={}
for v,k in zip([1,2,3,4],['b','c','d','e']):
    print(v,k)
    d[k]=v
print(d)

1 b
2 c
3 d
4 e
{'b': 1, 'c': 2, 'd': 3, 'e': 4}


In [67]:
dict(zip(['a','b'],[3,4]))

{'a': 3, 'b': 4}

In [68]:
students = { 'name': ['A','B','C','D','E'],
           'age': ['12','23','34','22','21'],
            'rollno':(1,2,3,4,5),
           'address': {'city':['bangalore','chennai','mumbai','delhi','kolkata'],
                      'state':['KA','TN','MH','DL','WB'],
                      'pin':[1,2,3,4,5]}}
students

{'name': ['A', 'B', 'C', 'D', 'E'],
 'age': ['12', '23', '34', '22', '21'],
 'rollno': (1, 2, 3, 4, 5),
 'address': {'city': ['bangalore', 'chennai', 'mumbai', 'delhi', 'kolkata'],
  'state': ['KA', 'TN', 'MH', 'DL', 'WB'],
  'pin': [1, 2, 3, 4, 5]}}

In [71]:
students['school_name'] = ['ABC','BCD','CDE','DEF','EFG','ddd']
students

{'name': ['A', 'B', 'C', 'D', 'E'],
 'age': ['12', '23', '34', '22', '21'],
 'rollno': (1, 2, 3, 4, 5),
 'address': {'area': ['a', 'b', 'c', 'd', 'e'],
  'city': ['bangalore', 'chennai', 'mumbai', 'delhi', 'kolkata'],
  'state': ['KA', 'TN', 'MH', 'DL', 'WB'],
  'pin': [1, 2, 3, 4, 5]},
 'school_name': ['ABC', 'BCD', 'CDE', 'DEF', 'EFG', 'ddd']}

In [70]:
students['address'] = {'area':['a','b','c','d','e'],
                       'city': ['bangalore', 'chennai', 'mumbai', 'delhi', 'kolkata'],
  'state': ['KA', 'TN', 'MH', 'DL', 'WB'],
  'pin': [1, 2, 3, 4, 5]}
students

{'name': ['A', 'B', 'C', 'D', 'E'],
 'age': ['12', '23', '34', '22', '21'],
 'rollno': (1, 2, 3, 4, 5),
 'address': {'area': ['a', 'b', 'c', 'd', 'e'],
  'city': ['bangalore', 'chennai', 'mumbai', 'delhi', 'kolkata'],
  'state': ['KA', 'TN', 'MH', 'DL', 'WB'],
  'pin': [1, 2, 3, 4, 5]},
 'school_name': ['ABC', 'BCD', 'CDE', 'DEF', 'EFG']}

In [78]:
for v in students.values():
    print(v)

['A', 'B', 'C', 'D', 'E']
['12', '23', '34', '22', '21']
(1, 2, 3, 4, 5)
{'area': ['a', 'b', 'c', 'd', 'e'], 'city': ['bangalore', 'chennai', 'mumbai', 'delhi', 'kolkata'], 'state': ['KA', 'TN', 'MH', 'DL', 'WB'], 'pin': [1, 2, 3, 4, 5]}
['ABC', 'BCD', 'CDE', 'DEF', 'EFG', 'ddd']


In [86]:
set1 = list(range(1,6))

In [87]:
print(set1)

[1, 2, 3, 4, 5]


In [88]:
print(set(set1))

{1, 2, 3, 4, 5}


In [91]:
s1 = set(range(1,6))
s2= set(range(4,10))

In [92]:
print(s1)
print(s2)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8, 9}


In [93]:
s1.intersection(s2)

{4, 5}

In [94]:
s2.intersection(s1)

{4, 5}

In [95]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [99]:
s2.difference(s1)

{6, 7, 8, 9}

In [104]:
list_ = []
for e in range(1,11):
    list_.append(e)
print(list_)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [106]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [107]:
[i**2 for i in range(1,6)]

[1, 4, 9, 16, 25]

In [126]:
sq_list = [[i, i**2] for i in range(1,31) if i%2==0]

In [128]:
# print(sq_list)
sq_list

[[2, 4],
 [4, 16],
 [6, 36],
 [8, 64],
 [10, 100],
 [12, 144],
 [14, 196],
 [16, 256],
 [18, 324],
 [20, 400],
 [22, 484],
 [24, 576],
 [26, 676],
 [28, 784],
 [30, 900]]

In [118]:
for i in range(1,5):
    print(i,i**2)

1 1
2 4
3 9
4 16


In [136]:
[i*2 for i in range(1,5)]# for j=2] #if j%2==0]

[2, 4, 6, 8]

In [137]:
my_list=[1,2,3,4,5]

In [138]:
import numpy as np

In [139]:
arr = np.array(my_list)

In [140]:
arr

array([1, 2, 3, 4, 5])

In [141]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [142]:
arr1=np.array(my_mat)

In [143]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [147]:
np.zeros(3)

array([0., 0., 0.])

In [150]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [153]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
np.linspace(1,99)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [169]:
np.eye(4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [172]:
np.random.rand(2,2,2)

array([[[0.99457017, 0.88961122],
        [0.36443856, 0.73620885]],

       [[0.6728008 , 0.1565547 ],
        [0.1239165 , 0.30937189]]])

In [177]:
np.random.randn(3,3)

array([[ 1.53512084,  0.38057107,  0.32952073],
       [ 1.7967169 , -0.11202029,  0.35879103],
       [ 1.10358271,  1.18946625,  0.37424187]])

In [181]:
np.random.randint(1,100,10)

array([54, 59, 52, 93, 25, 79, 45, 70, 62, 50])

In [219]:
arr = np.arange(25)

In [220]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [229]:
ranarr = np.random.randint(1,50,30)

In [230]:
ranarr

array([37,  6, 16, 49,  3,  2, 26, 48, 31, 41, 24, 47, 17, 47, 42, 26,  7,
        2, 44, 21, 19, 37, 46, 37, 32, 45, 23, 14, 14, 35])

In [205]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [206]:
np.random.randint(1,100,30).reshape(5,6)

array([[14, 14, 87, 93, 77, 88],
       [79, 18, 41, 94, 92, 43],
       [67, 61, 48,  6, 21, 60],
       [33, 88,  4, 37, 33, 17],
       [46, 62, 93, 39, 63, 22]])

In [207]:
(np.random.randint(1,100,30).reshape(5,6)).max()

95

In [203]:
ranarr.max()

37

In [208]:
ranarr

array([ 7, 34, 36, 11, 35,  4, 37,  7,  8, 32])

In [209]:
ranarr.argmax()

6

In [210]:
ranarr.argmin()

5

In [228]:
ranarr

array([29,  3,  9,  6, 20, 10, 41, 18, 49, 27, 42, 13, 31, 11, 23, 41, 29,
       47, 28, 30, 46,  6, 28, 26, 19, 35])

In [249]:
arr1=ranarr.reshape(5,6)

In [232]:
ranarr.dtype

dtype('int32')

In [233]:
import numpy as np

In [246]:
arr = np.arange(0,11)

In [247]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
arr[1:4]

array([1, 2, 3])

In [250]:
arr1

array([[37,  6, 16, 49,  3,  2],
       [26, 48, 31, 41, 24, 47],
       [17, 47, 42, 26,  7,  2],
       [44, 21, 19, 37, 46, 37],
       [32, 45, 23, 14, 14, 35]])

In [261]:
arr1[2:]

array([[17, 47, 42, 26,  7,  2],
       [44, 21, 19, 37, 46, 37],
       [32, 45, 23, 14, 14, 35]])

In [263]:
bool_arr=arr1>30

In [264]:
bool_arr

array([[ True, False, False,  True, False, False],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True, False, False, False],
       [ True, False, False,  True,  True,  True],
       [ True,  True, False, False, False,  True]])

In [265]:
arr1[bool_arr]

array([37, 49, 48, 31, 41, 47, 47, 42, 44, 37, 46, 37, 32, 45, 35])

In [268]:
arr1[arr1<4]

array([3, 2, 2])

In [284]:
arr_2d=np.random.randint(0,51,50).reshape(5,10)

In [285]:
arr_2d

array([[ 3, 37, 47, 25, 46,  4, 30, 35, 40, 16],
       [11, 48, 23, 18, 31, 32,  3, 18, 49, 12],
       [ 4, 24, 20, 30, 10, 46, 22, 14, 36,  6],
       [35, 37, 18, 18, 48,  3,  8,  0, 49, 37],
       [ 9, 20, 40, 40,  0, 13,  6, 49, 31, 42]])

In [291]:
arr_2d[1:4,8:]

array([[49, 12],
       [36,  6],
       [49, 37]])

In [292]:
arr_2d[arr_2d>45]

array([47, 46, 48, 49, 46, 48, 49, 49])

In [293]:
arr=np.arange(10)

In [294]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [296]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [297]:
arr+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [298]:
arr-20

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [299]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [301]:
arr/arr

C:\Users\pkmb\AppData\Local\Continuum\anaconda3_1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [303]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [304]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [305]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [306]:
np.max(arr)

9

In [307]:
arr.max()

9

In [309]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [310]:
np.log(arr)

C:\Users\pkmb\AppData\Local\Continuum\anaconda3_1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])